name: Build macOS

on: [push]

jobs:
  build:

    runs-on: macos-11
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: Install graphviz
        run: |
          brew install graphviz
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          python pyinstaller/extract_licenses.py
          pip install pyinstaller
      - name: Build using PyInstaller
        run: |
          pyinstaller blif2graph.spec
      - uses: actions/upload-artifact@v3
        with:
          name: blif2graph_macOS
          path: dist/
